# Generated by Django 2.2.7 on 2019-11-12 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0075_cable_devices'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualchassis',
            name='name',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
